app_name = "MyApp"

[features]
dark_mode = true
experimental = false
beta_features = ["feature1", "feature2", "feature3"]

[metadata]
version = "2.0.0"
author = "Jane Doe"
contributors = ["Alice", "Bob", "Charlie"]

[metadata.repository]
type = "git"
url = "https://github.com/oggiorgi.git"

[settings]
theme = "dark"
languages = ["English", "Spanish", "German"]

[settings.notifications]
email = true
sms = false
push = true